export const ADMIN_ROLES = {
  COMPANY_ADMIN: 'admin',
  FINANCE: 'finance',
  SUPPORT: 'support',
  AUDITOR: 'auditor',
};

export const KPIS = [
  { id: 'orders', label: 'Orders Today', value: '1,284', delta: '+12.4%', trend: 'up', tone: 'blue' },
  { id: 'vendors', label: 'Active Vendors', value: '24 / 26', delta: '+2 active', trend: 'up', tone: 'green' },
  { id: 'failed', label: 'Failed Payments', value: '7', delta: '-3 vs yest.', trend: 'down', tone: 'amber' },
  { id: 'revenue', label: 'Revenue Today', value: 'R 48,260', delta: '+8.1%', trend: 'up', tone: 'blue' },
];

export const ORDER_VOLUME_TREND = [
  { day: 'Mon', orders: 920, revenue: 38400 },
  { day: 'Tue', orders: 1050, revenue: 41200 },
  { day: 'Wed', orders: 1180, revenue: 44900 },
  { day: 'Thu', orders: 1320, revenue: 49200 },
  { day: 'Fri', orders: 1284, revenue: 48260 },
  { day: 'Sat', orders: 740, revenue: 28100 },
  { day: 'Sun', orders: 620, revenue: 23800 },
];

export const ORDER_STATUS_BREAKDOWN = [
  { name: 'Completed', value: 1042, color: '#22A559' },
  { name: 'Ready', value: 142, color: '#0A8CFF' },
  { name: 'Preparing', value: 58, color: '#5FB1FF' },
  { name: 'Pending', value: 24, color: '#D99A00' },
  { name: 'Cancelled', value: 18, color: '#D94A4A' },
];

export const VENDOR_PERFORMANCE = [
  { name: 'Library Bistro', orders: 224, revenue: 11240 },
  { name: 'Main Campus Cafe', orders: 198, revenue: 9980 },
  { name: 'Dining Hall', orders: 176, revenue: 9100 },
  { name: 'Grill House', orders: 152, revenue: 7800 },
  { name: 'Res Court', orders: 134, revenue: 6820 },
];

export const RECENT_ACTIVITY = [
  { id: 'a1', actor: 'System', action: 'Resolved delayed order', target: 'Order #48210', time: '2 min ago', tone: 'success' },
  { id: 'a2', actor: 'Thabo M.', action: 'Approved vendor onboarding', target: 'Fresh at First', time: '18 min ago', tone: 'info' },
  { id: 'a3', actor: 'Support', action: 'Refunded payment', target: 'Order #48198', time: '42 min ago', tone: 'warning' },
  { id: 'a4', actor: 'Lerato K.', action: 'Activated vendor', target: 'Woolworths Food Stop', time: '1 hr ago', tone: 'success' },
  { id: 'a5', actor: 'System', action: 'Flagged suspicious login', target: 'user@merchantplace.local', time: '2 hr ago', tone: 'error' },
];

export const FAILED_PAYMENTS = [
  { id: 'f1', order: '#48213', amount: 'R 142.50', reason: 'Card declined', vendor: 'Library Bistro' },
  { id: 'f2', order: '#48208', amount: 'R 86.00', reason: 'Insufficient funds', vendor: 'Main Campus Cafe' },
  { id: 'f3', order: '#48197', amount: 'R 210.00', reason: 'Card expired', vendor: 'Dining Hall' },
];

export const TOP_CAFETERIAS = [
  { id: 'main-campus-cafe', name: 'Main Campus Cafe', status: 'open', ordersToday: 198, rating: 4.6 },
  { id: 'library-bistro', name: 'Library Bistro', status: 'busy', ordersToday: 224, rating: 4.8 },
  { id: 'dining-hall-central', name: 'Dining Hall Central', status: 'open', ordersToday: 176, rating: 4.6 },
  { id: 'grill-house-court', name: 'Grill House Court', status: 'open', ordersToday: 152, rating: 4.5 },
];

export const PENDING_VENDOR_APPROVALS = [
  {
    id: 'v1',
    name: 'Vovo Telo',
    slug: 'vovo-telo',
    description: 'Artisan coffee, fresh pastries, and breakfast bowls crafted with locally sourced ingredients.',
    logo_url: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=400',
    campus: 'Main site',
    building: 'Atrium',
    contactName: 'Lerato Khumalo',
    contactEmail: 'lerato@vovo.merchantmunnies.local',
    contactPhone: '+27 11 555 0142',
    cateringEnabled: true,
    categories: ['Breakfast & Brunch', 'Coffee & Bakery'],
    submittedAt: '2026-09-01 · 09:14',
    documents: ['business-registration.pdf', 'health-certificate.pdf', 'menu.pdf'],
    operatingHours: 'Mon–Fri · 06:30 – 17:00',
    estimatedPrep: '10–15 min',
  },
  {
    id: 'v2',
    name: 'Merchant Munchies Express',
    slug: 'merchant-munchies-express',
    description: 'A grab-and-go kiosk focused on quick-bite meals for busy teams.',
    logo_url: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400',
    campus: 'North site',
    building: 'Library Concourse',
    contactName: 'Sipho Dlamini',
    contactEmail: 'sipho@express.merchantmunnies.local',
    contactPhone: '+27 11 555 0218',
    cateringEnabled: false,
    categories: ['Quick Bites', 'Wraps'],
    submittedAt: '2026-08-31 · 16:22',
    documents: ['business-registration.pdf', 'menu.pdf'],
    operatingHours: 'Mon–Fri · 07:00 – 16:00',
    estimatedPrep: '5–8 min',
  },
  {
    id: 'v3',
    name: 'Woolworths Food Stop',
    slug: 'woolworths-food-stop',
    description: 'Curated, ready-to-heat meals, salads and snacks from the Woolworths tasting range.',
    logo_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400',
    campus: 'South site',
    building: 'Eastgate Concourse',
    contactName: 'Ayanda Maseko',
    contactEmail: 'ayanda@wwfs.merchantmunnies.local',
    contactPhone: '+27 11 555 0411',
    cateringEnabled: true,
    categories: ['Groceries', 'Healthy', 'Snacks'],
    submittedAt: '2026-08-30 · 11:05',
    documents: ['business-registration.pdf', 'health-certificate.pdf', 'product-list.pdf', 'menu.pdf'],
    operatingHours: 'Mon–Fri · 07:30 – 18:00',
    estimatedPrep: '4–7 min',
  },
];

export const ACTIVE_VENDORS = [
  {
    id: 'main-campus-cafe',
    name: 'Main Campus Cafe',
    slug: 'main-campus-cafe',
    description: 'Our flagship house-roasted coffee, salads, hot meals and sweet treats just off the atrium.',
    logo_url: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=400',
    campus: 'Main site',
    building: 'Atrium',
    status: 'open',
    serviceStatus: 'open',
    cateringEnabled: true,
    rating: 4.6,
    ratingCount: 230,
    ordersToday: 198,
    revenue30d: 184260,
    categories: ['Breakfast', 'Lunch', 'Coffee'],
    contactEmail: 'maincampus@merchantmunnies.local',
    contactPhone: '+27 11 555 0101',
    manager: 'Nomvula Dube',
    menuItems: 84,
    operatingHours: 'Mon–Fri · 06:30 – 18:00',
    estimatedPrep: '12–18 min',
    createdAt: '2025-04-12',
  },
  {
    id: 'library-bistro',
    name: 'Library Bistro',
    slug: 'library-bistro',
    description: 'A calm, library-side bistro serving comfort bowls, smoothies and quiet study-friendly bites.',
    logo_url: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400',
    campus: 'North site',
    building: 'Library Level 2',
    status: 'busy',
    serviceStatus: 'busy',
    cateringEnabled: true,
    rating: 4.8,
    ratingCount: 184,
    ordersToday: 224,
    revenue30d: 198420,
    categories: ['Breakfast', 'Lunch', 'Smoothies'],
    contactEmail: 'library@merchantmunnies.local',
    contactPhone: '+27 11 555 0123',
    manager: 'Thuli Mokoena',
    menuItems: 62,
    operatingHours: 'Mon–Sat · 07:00 – 17:00',
    estimatedPrep: '10–15 min',
    createdAt: '2025-06-04',
  },
  {
    id: 'dining-hall-central',
    name: 'Dining Hall Central',
    slug: 'dining-hall-central',
    description: 'Our largest venue. Varied hot meals, carvery and a salad bar with rotating daily specials.',
    logo_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=400',
    campus: 'Main site',
    building: 'Central Hall',
    status: 'open',
    serviceStatus: 'open',
    cateringEnabled: true,
    rating: 4.6,
    ratingCount: 301,
    ordersToday: 176,
    revenue30d: 152930,
    categories: ['Breakfast', 'Lunch', 'Dinner'],
    contactEmail: 'dininghall@merchantmunnies.local',
    contactPhone: '+27 11 555 0144',
    manager: 'Karabo Nkosi',
    menuItems: 120,
    operatingHours: 'Mon–Fri · 06:30 – 20:00',
    estimatedPrep: '15–22 min',
    createdAt: '2025-02-28',
  },
  {
    id: 'grill-house-court',
    name: 'Grill House Court',
    slug: 'grill-house-court',
    description: 'Open-flame grilled chicken, ribs and burgers — a courtyard favourite.',
    logo_url: 'https://images.unsplash.com/photo-1558030006-450675393462?w=400',
    campus: 'Main site',
    building: 'Courtyard',
    status: 'open',
    serviceStatus: 'open',
    cateringEnabled: true,
    rating: 4.5,
    ratingCount: 212,
    ordersToday: 152,
    revenue30d: 141890,
    categories: ['Lunch', 'Meals'],
    contactEmail: 'grillhouse@merchantmunnies.local',
    contactPhone: '+27 11 555 0166',
    manager: 'Jason Pillay',
    menuItems: 48,
    operatingHours: 'Mon–Fri · 10:00 – 17:00',
    estimatedPrep: '14–20 min',
    createdAt: '2025-08-19',
  },
  {
    id: 'res-court-kitchen',
    name: 'Residence Court Kitchen',
    slug: 'res-court-kitchen',
    description: 'Comfort meals for residence students, with rotating specials and late-night service.',
    logo_url: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400',
    campus: 'South site',
    building: 'Residence Court',
    status: 'open',
    serviceStatus: 'open',
    cateringEnabled: false,
    rating: 4.7,
    ratingCount: 156,
    ordersToday: 134,
    revenue30d: 122480,
    categories: ['Lunch', 'Dinner', 'Meals'],
    contactEmail: 'rescourt@merchantmunnies.local',
    contactPhone: '+27 11 555 0188',
    manager: 'Naledi Botha',
    menuItems: 56,
    operatingHours: 'Mon–Sun · 11:00 – 22:00',
    estimatedPrep: '12–18 min',
    createdAt: '2025-09-02',
  },
  {
    id: 'science-snack-bar',
    name: 'Science Snack Bar',
    slug: 'science-snack-bar',
    description: 'Quick snacks, smoothies and protein shakes for the Science building crowd.',
    logo_url: 'https://images.unsplash.com/photo-1626197031507-c17099753291?w=400',
    campus: 'North site',
    building: 'Science Building',
    status: 'closed',
    serviceStatus: 'closed',
    cateringEnabled: false,
    rating: 4.4,
    ratingCount: 98,
    ordersToday: 0,
    revenue30d: 78430,
    categories: ['Snacks', 'Drinks'],
    contactEmail: 'science@merchantmunnies.local',
    contactPhone: '+27 11 555 0202',
    manager: 'Mpho Sithole',
    menuItems: 36,
    operatingHours: 'Mon–Fri · 08:00 – 16:00',
    estimatedPrep: '5–10 min',
    createdAt: '2025-11-14',
  },
];

export const ORDER_STATUS = {
  PAYMENT_PENDING: 'payment_pending',
  SUBMITTED: 'submitted',
  PAYMENT_CONFIRMED: 'payment_confirmed',
  RECEIVED_BY_VENDOR: 'received_by_vendor',
  ACCEPTED: 'accepted',
  PREPARING: 'preparing',
  READY_FOR_COLLECTION: 'ready_for_collection',
  COLLECTED: 'collected',
  COMPLETED: 'completed',
  CANCELLED: 'cancelled',
  REJECTED: 'rejected',
  REFUND_PENDING: 'refund_pending',
  REFUNDED: 'refunded',
  COLLECTION_NOT_COMPLETED: 'collection_not_completed',
};

export const ORDER_STATUS_LABELS = {
  [ORDER_STATUS.PAYMENT_PENDING]: 'Payment Pending',
  [ORDER_STATUS.SUBMITTED]: 'Submitted',
  [ORDER_STATUS.PAYMENT_CONFIRMED]: 'Payment Confirmed',
  [ORDER_STATUS.RECEIVED_BY_VENDOR]: 'Received',
  [ORDER_STATUS.ACCEPTED]: 'Accepted',
  [ORDER_STATUS.PREPARING]: 'Preparing',
  [ORDER_STATUS.READY_FOR_COLLECTION]: 'Ready',
  [ORDER_STATUS.COLLECTED]: 'Collected',
  [ORDER_STATUS.COMPLETED]: 'Completed',
  [ORDER_STATUS.CANCELLED]: 'Cancelled',
  [ORDER_STATUS.REJECTED]: 'Rejected',
  [ORDER_STATUS.REFUND_PENDING]: 'Refund Pending',
  [ORDER_STATUS.REFUNDED]: 'Refunded',
  [ORDER_STATUS.COLLECTION_NOT_COMPLETED]: 'Not Collected',
};

export const ORDER_STATUS_TONES = {
  [ORDER_STATUS.PAYMENT_PENDING]: 'warning',
  [ORDER_STATUS.SUBMITTED]: 'info',
  [ORDER_STATUS.PAYMENT_CONFIRMED]: 'info',
  [ORDER_STATUS.RECEIVED_BY_VENDOR]: 'info',
  [ORDER_STATUS.ACCEPTED]: 'info',
  [ORDER_STATUS.PREPARING]: 'info',
  [ORDER_STATUS.READY_FOR_COLLECTION]: 'blue',
  [ORDER_STATUS.COLLECTED]: 'success',
  [ORDER_STATUS.COMPLETED]: 'success',
  [ORDER_STATUS.CANCELLED]: 'error',
  [ORDER_STATUS.REJECTED]: 'error',
  [ORDER_STATUS.REFUND_PENDING]: 'warning',
  [ORDER_STATUS.REFUNDED]: 'success',
  [ORDER_STATUS.COLLECTION_NOT_COMPLETED]: 'error',
};

export const ORDER_STATUS_FILTERS = [
  { id: 'all', label: 'All' },
  { id: 'active', label: 'Active' },
  { id: 'preparing', label: 'Preparing' },
  { id: 'ready', label: 'Ready' },
  { id: 'completed', label: 'Completed' },
  { id: 'issue', label: 'Needs attention' },
];

export const ADMIN_ORDERS = [
  {
    id: '48213',
    customerName: 'Thabo Mokoena',
    customerNumber: 'EMP-10234',
    vendorName: 'Library Bistro',
    vendorId: 'library-bistro',
    status: ORDER_STATUS.PREPARING,
    items: 4,
    total: 215.0,
    paymentMethod: 'Bank Card',
    paymentStatus: 'succeeded',
    placedAt: '2026-09-01T12:18:00Z',
    collectionSlot: 'Today · 12:45 – 13:00',
    collectionPoint: 'Library Bistro – Pickup Counter',
    flags: [],
    timeline: [
      { status: 'submitted', at: '12:18', actor: 'Customer' },
      { status: 'payment_confirmed', at: '12:18', actor: 'System' },
      { status: 'received_by_vendor', at: '12:20', actor: 'Vendor' },
      { status: 'accepted', at: '12:21', actor: 'Vendor' },
      { status: 'preparing', at: '12:24', actor: 'Vendor' },
    ],
  },
  {
    id: '48211',
    customerName: 'Ayanda Sithole',
    customerNumber: 'EMP-10142',
    vendorName: 'Main Campus Cafe',
    vendorId: 'main-campus-cafe',
    status: ORDER_STATUS.COLLECTED,
    items: 3,
    total: 142.5,
    paymentMethod: 'Digital Wallet',
    paymentStatus: 'succeeded',
    placedAt: '2026-09-01T11:48:00Z',
    collectionSlot: 'Today · 12:00 – 12:15',
    collectionPoint: 'Atrium – Counter A',
    flags: [],
    timeline: [
      { status: 'submitted', at: '11:48', actor: 'Customer' },
      { status: 'payment_confirmed', at: '11:48', actor: 'System' },
      { status: 'preparing', at: '11:50', actor: 'Vendor' },
      { status: 'ready_for_collection', at: '11:58', actor: 'Vendor' },
      { status: 'collected', at: '12:04', actor: 'Vendor' },
      { status: 'completed', at: '12:04', actor: 'System' },
    ],
  },
  {
    id: '48208',
    customerName: 'Lerato Khumalo',
    customerNumber: 'EMP-10512',
    vendorName: 'Grill House Court',
    vendorId: 'grill-house-court',
    status: ORDER_STATUS.READY_FOR_COLLECTION,
    items: 2,
    total: 86.0,
    paymentMethod: 'Bank Card',
    paymentStatus: 'succeeded',
    placedAt: '2026-09-01T11:32:00Z',
    collectionSlot: 'Today · 12:00 – 12:15',
    collectionPoint: 'Courtyard – Pickup',
    flags: [],
    timeline: [
      { status: 'submitted', at: '11:32', actor: 'Customer' },
      { status: 'payment_confirmed', at: '11:32', actor: 'System' },
      { status: 'preparing', at: '11:34', actor: 'Vendor' },
      { status: 'ready_for_collection', at: '11:55', actor: 'Vendor' },
    ],
  },
  {
    id: '48204',
    customerName: 'Sipho Dlamini',
    customerNumber: 'EMP-10311',
    vendorName: 'Dining Hall Central',
    vendorId: 'dining-hall-central',
    status: ORDER_STATUS.PAYMENT_PENDING,
    items: 2,
    total: 64.5,
    paymentMethod: 'Bank Card',
    paymentStatus: 'pending',
    placedAt: '2026-09-01T11:14:00Z',
    collectionSlot: 'Today · 11:45 – 12:00',
    collectionPoint: 'Central Hall – Counter 2',
    flags: ['urgent'],
    timeline: [
      { status: 'submitted', at: '11:14', actor: 'Customer' },
      { status: 'payment_pending', at: '11:14', actor: 'System' },
    ],
  },
  {
    id: '48201',
    customerName: 'Naledi Botha',
    customerNumber: 'EMP-10045',
    vendorName: 'Main Campus Cafe',
    vendorId: 'main-campus-cafe',
    status: ORDER_STATUS.PREPARING,
    items: 6,
    total: 342.0,
    paymentMethod: 'Cost Centre',
    paymentStatus: 'succeeded',
    placedAt: '2026-09-01T10:48:00Z',
    collectionSlot: 'Today · 11:30 – 11:45',
    collectionPoint: 'Atrium – Counter A',
    flags: ['corporate'],
    timeline: [
      { status: 'submitted', at: '10:48', actor: 'Customer' },
      { status: 'payment_confirmed', at: '10:48', actor: 'System' },
      { status: 'preparing', at: '10:52', actor: 'Vendor' },
    ],
  },
  {
    id: '48198',
    customerName: 'Karabo Nkosi',
    customerNumber: 'EMP-10062',
    vendorName: 'Library Bistro',
    vendorId: 'library-bistro',
    status: ORDER_STATUS.REFUND_PENDING,
    items: 3,
    total: 118.0,
    paymentMethod: 'Bank Card',
    paymentStatus: 'refunded',
    placedAt: '2026-09-01T10:22:00Z',
    collectionSlot: 'Today · 11:00 – 11:15',
    collectionPoint: 'Library Bistro – Pickup Counter',
    flags: ['refund'],
    timeline: [
      { status: 'submitted', at: '10:22', actor: 'Customer' },
      { status: 'payment_confirmed', at: '10:22', actor: 'System' },
      { status: 'rejected', at: '10:35', actor: 'Vendor', reason: 'Out of stock' },
      { status: 'refund_pending', at: '10:36', actor: 'System' },
    ],
  },
  {
    id: '48192',
    customerName: 'Nomvula Dube',
    customerNumber: 'EMP-10222',
    vendorName: 'Residence Court Kitchen',
    vendorId: 'res-court-kitchen',
    status: ORDER_STATUS.COLLECTION_NOT_COMPLETED,
    items: 2,
    total: 78.0,
    paymentMethod: 'Bank Card',
    paymentStatus: 'succeeded',
    placedAt: '2026-08-31T19:48:00Z',
    collectionSlot: 'Yesterday · 20:00 – 20:15',
    collectionPoint: 'Residence Court – Pickup',
    flags: ['uncollected'],
    timeline: [
      { status: 'submitted', at: '19:48', actor: 'Customer' },
      { status: 'payment_confirmed', at: '19:48', actor: 'System' },
      { status: 'ready_for_collection', at: '19:55', actor: 'Vendor' },
      { status: 'collection_not_completed', at: '20:30', actor: 'System', reason: 'Customer did not collect' },
    ],
  },
  {
    id: '48185',
    customerName: 'Nompilo Cele',
    customerNumber: 'EMP-10155',
    vendorName: 'Grill House Court',
    vendorId: 'grill-house-court',
    status: ORDER_STATUS.CANCELLED,
    items: 1,
    total: 42.0,
    paymentMethod: 'Bank Card',
    paymentStatus: 'refunded',
    placedAt: '2026-08-31T13:14:00Z',
    collectionSlot: 'Yesterday · 13:45 – 14:00',
    collectionPoint: 'Courtyard – Pickup',
    flags: ['cancelled'],
    timeline: [
      { status: 'submitted', at: '13:14', actor: 'Customer' },
      { status: 'cancelled', at: '13:18', actor: 'Customer', reason: 'Customer cancelled before cutoff' },
      { status: 'refunded', at: '13:22', actor: 'System' },
    ],
  },
  {
    id: '48180',
    customerName: 'Jason Pillay',
    customerNumber: 'EMP-10402',
    vendorName: 'Dining Hall Central',
    vendorId: 'dining-hall-central',
    status: ORDER_STATUS.COMPLETED,
    items: 3,
    total: 154.0,
    paymentMethod: 'Digital Wallet',
    paymentStatus: 'succeeded',
    placedAt: '2026-08-31T11:48:00Z',
    collectionSlot: 'Yesterday · 12:30 – 12:45',
    collectionPoint: 'Central Hall – Counter 1',
    flags: [],
    timeline: [
      { status: 'submitted', at: '11:48', actor: 'Customer' },
      { status: 'payment_confirmed', at: '11:48', actor: 'System' },
      { status: 'preparing', at: '11:52', actor: 'Vendor' },
      { status: 'ready_for_collection', at: '12:24', actor: 'Vendor' },
      { status: 'collected', at: '12:32', actor: 'Vendor' },
    ],
  },
  {
    id: '48174',
    customerName: 'Lerato Khumalo',
    customerNumber: 'EMP-10512',
    vendorName: 'Science Snack Bar',
    vendorId: 'science-snack-bar',
    status: ORDER_STATUS.REJECTED,
    items: 5,
    total: 196.0,
    paymentMethod: 'Bank Card',
    paymentStatus: 'refunded',
    placedAt: '2026-08-31T09:32:00Z',
    collectionSlot: 'Yesterday · 10:00 – 10:15',
    collectionPoint: 'Science Building – Counter',
    flags: ['rejected'],
    timeline: [
      { status: 'submitted', at: '09:32', actor: 'Customer' },
      { status: 'payment_confirmed', at: '09:32', actor: 'System' },
      { status: 'rejected', at: '09:38', actor: 'Vendor', reason: 'Vendor temporarily unavailable' },
    ],
  },
];

export const ORDER_STATUS_FILTER_MATCH = {
  all: () => true,
  active: (order) => [ORDER_STATUS.PAYMENT_PENDING, ORDER_STATUS.SUBMITTED, ORDER_STATUS.PAYMENT_CONFIRMED, ORDER_STATUS.RECEIVED_BY_VENDOR, ORDER_STATUS.ACCEPTED, ORDER_STATUS.PREPARING, ORDER_STATUS.READY_FOR_COLLECTION].includes(order.status),
  preparing: (order) => order.status === ORDER_STATUS.PREPARING,
  ready: (order) => order.status === ORDER_STATUS.READY_FOR_COLLECTION,
  completed: (order) => [ORDER_STATUS.COLLECTED, ORDER_STATUS.COMPLETED].includes(order.status),
  issue: (order) => [ORDER_STATUS.PAYMENT_PENDING, ORDER_STATUS.REFUND_PENDING, ORDER_STATUS.CANCELLED, ORDER_STATUS.REJECTED, ORDER_STATUS.COLLECTION_NOT_COMPLETED].includes(order.status),
};

export const ADMIN_PLATFORM_USERS = [
  {
    id: 'u1',
    name: 'Thabo Mokoena',
    email: 'thabo@merchantmunnies.local',
    number: 'EMP-10234',
    roles: ['employee'],
    status: 'active',
    lastSeen: '5 min ago',
    site: 'Main site',
    building: 'Atrium',
    orders: 142,
    joinedAt: '2025-08-14',
    dietary: ['Halal'],
    favourites: ['library-bistro', 'grill-house-court'],
    cardOnFile: true,
  },
  {
    id: 'u2',
    name: 'Lerato Khumalo',
    email: 'lerato@vovo.merchantmunnies.local',
    number: 'VND-00012',
    roles: ['vendor_manager'],
    status: 'active',
    lastSeen: '12 min ago',
    site: 'Main site',
    building: 'Atrium',
    orders: 0,
    joinedAt: '2025-04-02',
    vendor: 'Vovo Telo (pending approval)',
    dietary: [],
    favourites: [],
    cardOnFile: false,
  },
  {
    id: 'u3',
    name: 'Thuli Mokoena',
    email: 'thuli@librarybistro.local',
    number: 'VND-00018',
    roles: ['vendor_manager'],
    status: 'active',
    lastSeen: '1 hr ago',
    site: 'North site',
    building: 'Library Level 2',
    orders: 0,
    joinedAt: '2025-06-12',
    vendor: 'Library Bistro',
    dietary: [],
    favourites: [],
    cardOnFile: false,
  },
  {
    id: 'u4',
    name: 'Nomvula Dube',
    email: 'nomvula.admin@merchantmunnies.local',
    number: 'ADM-00001',
    roles: ['admin'],
    status: 'active',
    lastSeen: 'Now',
    site: 'Main site',
    building: 'Central Tower',
    orders: 0,
    joinedAt: '2024-11-08',
    dietary: [],
    favourites: [],
    cardOnFile: false,
  },
  {
    id: 'u5',
    name: 'Karabo Nkosi',
    email: 'karabo@merchantmunnies.local',
    number: 'EMP-10062',
    roles: ['employee', 'executive_assistant'],
    status: 'active',
    lastSeen: '20 min ago',
    site: 'Main site',
    building: 'Central Tower',
    orders: 87,
    joinedAt: '2024-09-23',
    dietary: ['Vegetarian', 'Gluten-conscious'],
    favourites: ['main-campus-cafe'],
    cardOnFile: true,
  },
  {
    id: 'u6',
    name: 'Sipho Dlamini',
    email: 'sipho@express.local',
    number: 'VND-00022',
    roles: ['vendor_staff'],
    status: 'pending',
    lastSeen: 'Never',
    site: 'North site',
    building: 'Library Concourse',
    orders: 0,
    joinedAt: '2026-08-31',
    vendor: 'Merchant Munchies Express (pending)',
    dietary: [],
    favourites: [],
    cardOnFile: false,
  },
  {
    id: 'u7',
    name: 'Ayanda Sithole',
    email: 'ayanda@finance.local',
    number: 'FIN-00004',
    roles: ['finance'],
    status: 'active',
    lastSeen: '2 hr ago',
    site: 'Main site',
    building: 'Central Tower',
    orders: 0,
    joinedAt: '2025-01-15',
    dietary: [],
    favourites: [],
    cardOnFile: false,
  },
  {
    id: 'u8',
    name: 'Mpho Sithole',
    email: 'mpho@merchantmunnies.local',
    number: 'EMP-10082',
    roles: ['employee'],
    status: 'inactive',
    lastSeen: '2 weeks ago',
    site: 'South site',
    building: 'Eastgate Concourse',
    orders: 24,
    joinedAt: '2024-06-04',
    dietary: ['Vegan'],
    favourites: ['science-snack-bar'],
    cardOnFile: true,
  },
];

export const USER_STATUS_FILTERS = [
  { id: 'all', label: 'All' },
  { id: 'active', label: 'Active' },
  { id: 'pending', label: 'Pending' },
  { id: 'inactive', label: 'Inactive' },
];

export const ROLE_FILTERS = [
  { id: 'all', label: 'All roles' },
  { id: 'employee', label: 'Employee' },
  { id: 'vendor', label: 'Vendor' },
  { id: 'finance', label: 'Finance' },
  { id: 'support', label: 'Support' },
  { id: 'admin', label: 'Admin' },
];

export const ROLE_FILTER_MATCH = {
  all: () => true,
  employee: (u) => u.roles.some((r) => ['employee', 'executive_assistant', 'event_organiser'].includes(r)),
  vendor: (u) => u.roles.some((r) => ['vendor_staff', 'vendor_manager'].includes(r)),
  finance: (u) => u.roles.includes('finance'),
  support: (u) => u.roles.includes('support'),
  admin: (u) => u.roles.includes('admin'),
};

export const ALL_ROLES = [
  { id: 'employee', label: 'Employee', tone: 'info' },
  { id: 'executive_assistant', label: 'Executive Assistant', tone: 'info' },
  { id: 'event_organiser', label: 'Event Organiser', tone: 'info' },
  { id: 'vendor_staff', label: 'Vendor Staff', tone: 'success' },
  { id: 'vendor_manager', label: 'Vendor Manager', tone: 'success' },
  { id: 'finance', label: 'Finance', tone: 'warning' },
  { id: 'support', label: 'Support', tone: 'warning' },
  { id: 'admin', label: 'Company Admin', tone: 'error' },
];


export const ADMIN_NAV_ITEMS = [
  { id: 'dashboard', label: 'Dashboard', to: '/admin', icon: 'IconChartBar' },
  { id: 'vendors', label: 'Vendors', to: '/admin/vendors', icon: 'IconBuildingStore' },
  { id: 'cafeterias', label: 'Cafeterias', to: '/admin/cafeterias', icon: 'IconMapPin' },
  { id: 'users', label: 'Users & Roles', to: '/admin/users', icon: 'IconUsers' },
  { id: 'orders', label: 'Orders', to: '/admin/orders', icon: 'IconReceipt' },
  { id: 'reports', label: 'Reports', to: '/admin/reports', icon: 'IconFileAnalytics' },
  { id: 'complaints', label: 'Complaints', to: '/admin/complaints', icon: 'IconAlertTriangle' },
  { id: 'announcements', label: 'Announcements', to: '/admin/announcements', icon: 'IconSpeakerphone' },
  { id: 'audit', label: 'Audit Logs', to: '/admin/audit', icon: 'IconShieldCheck' },
  { id: 'settings', label: 'Settings', to: '/admin/settings', icon: 'IconSettings' },
];

export const ADMIN_SITES = [
  {
    id: 'site-main',
    name: 'Merchant Place · Main',
    code: 'MP-MAIN',
    address: '1 Merchant Place, Sandton, Johannesburg, 2196',
    timezone: 'Africa/Johannesburg',
    isActive: true,
    buildings: 4,
    vendors: 4,
    collectionPoints: 7,
    ordersToday: 542,
    orderVolume30d: 412480,
    coordinates: { lat: -26.1076, lng: 28.0567 },
    createdAt: '2025-01-15',
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800',
  },
  {
    id: 'site-north',
    name: 'Merchant Place · North Campus',
    code: 'MP-NORTH',
    address: '24 Fredman Drive, Sandton, Johannesburg, 2196',
    timezone: 'Africa/Johannesburg',
    isActive: true,
    buildings: 3,
    vendors: 2,
    collectionPoints: 5,
    ordersToday: 412,
    orderVolume30d: 318420,
    coordinates: { lat: -26.1044, lng: 28.0531 },
    createdAt: '2025-03-08',
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800',
  },
  {
    id: 'site-south',
    name: 'Merchant Place · South Residence',
    code: 'MP-SOUTH',
    address: '5 West Street, Sandton, Johannesburg, 2196',
    timezone: 'Africa/Johannesburg',
    isActive: true,
    buildings: 2,
    vendors: 2,
    collectionPoints: 4,
    ordersToday: 198,
    orderVolume30d: 142630,
    coordinates: { lat: -26.1095, lng: 28.0498 },
    createdAt: '2025-05-22',
    image: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=800',
  },
  {
    id: 'site-pilot-sandton',
    name: 'Sandton Pilot',
    code: 'PILOT-SANDTON',
    address: 'Sandton Convention District · Coming soon',
    timezone: 'Africa/Johannesburg',
    isActive: false,
    buildings: 0,
    vendors: 0,
    collectionPoints: 0,
    ordersToday: 0,
    orderVolume30d: 0,
    coordinates: { lat: -26.1085, lng: 28.0561 },
    createdAt: '2026-08-12',
    image: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=800',
  },
];

export const ADMIN_BUILDINGS = [
  // Main site
  {
    id: 'b-main-atrium',
    siteId: 'site-main',
    siteName: 'Merchant Place · Main',
    name: 'Atrium',
    code: 'M-ATR',
    address: 'Ground floor, 1 Merchant Place',
    isActive: true,
    floors: 2,
    collectionPoints: 3,
    vendors: 2,
    ordersToday: 248,
    coords: { lat: -26.1075, lng: 28.0568 },
    images: ['https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=400'],
  },
  {
    id: 'b-main-central',
    siteId: 'site-main',
    siteName: 'Merchant Place · Main',
    name: 'Central Tower',
    code: 'M-CTR',
    address: 'Tower block, 1 Merchant Place',
    isActive: true,
    floors: 12,
    collectionPoints: 2,
    vendors: 1,
    ordersToday: 184,
    coords: { lat: -26.1077, lng: 28.0566 },
    images: ['https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=400'],
  },
  {
    id: 'b-main-courtyard',
    siteId: 'site-main',
    siteName: 'Merchant Place · Main',
    name: 'Courtyard',
    code: 'M-CRT',
    address: 'South wing ground floor, 1 Merchant Place',
    isActive: true,
    floors: 1,
    collectionPoints: 1,
    vendors: 1,
    ordersToday: 88,
    coords: { lat: -26.1078, lng: 28.0569 },
    images: ['https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=400'],
  },
  {
    id: 'b-main-east',
    siteId: 'site-main',
    siteName: 'Merchant Place · Main',
    name: 'East Pavilion',
    code: 'M-EAS',
    address: 'East pavilion, 1 Merchant Place',
    isActive: false,
    floors: 3,
    collectionPoints: 1,
    vendors: 0,
    ordersToday: 0,
    coords: { lat: -26.1076, lng: 28.0570 },
    images: [],
  },
  // North site
  {
    id: 'b-north-library',
    siteId: 'site-north',
    siteName: 'Merchant Place · North Campus',
    name: 'Library',
    code: 'N-LIB',
    address: 'Knowledge Centre, 24 Fredman Drive',
    isActive: true,
    floors: 4,
    collectionPoints: 3,
    vendors: 1,
    ordersToday: 264,
    coords: { lat: -26.1044, lng: 28.0531 },
    images: ['https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=400'],
  },
  {
    id: 'b-north-science',
    siteId: 'site-north',
    siteName: 'Merchant Place · North Campus',
    name: 'Science Building',
    code: 'N-SCI',
    address: 'Innovation wing, 24 Fredman Drive',
    isActive: true,
    floors: 5,
    collectionPoints: 2,
    vendors: 1,
    ordersToday: 148,
    coords: { lat: -26.1042, lng: 28.0530 },
    images: ['https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=400'],
  },
  {
    id: 'b-north-concourse',
    siteId: 'site-north',
    siteName: 'Merchant Place · North Campus',
    name: 'Concourse',
    code: 'N-CON',
    address: 'Connecting wing, 24 Fredman Drive',
    isActive: false,
    floors: 2,
    collectionPoints: 0,
    vendors: 0,
    ordersToday: 0,
    coords: { lat: -26.1045, lng: 28.0532 },
    images: [],
  },
  // South site
  {
    id: 'b-south-res',
    siteId: 'site-south',
    siteName: 'Merchant Place · South Residence',
    name: 'Residence Court',
    code: 'S-RES',
    address: 'Main residence block, 5 West Street',
    isActive: true,
    floors: 8,
    collectionPoints: 3,
    vendors: 1,
    ordersToday: 134,
    coords: { lat: -26.1095, lng: 28.0498 },
    images: ['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=400'],
  },
  {
    id: 'b-south-eastgate',
    siteId: 'site-south',
    siteName: 'Merchant Place · South Residence',
    name: 'Eastgate Concourse',
    code: 'S-EGT',
    address: 'Eastgate block, 5 West Street',
    isActive: true,
    floors: 3,
    collectionPoints: 1,
    vendors: 1,
    ordersToday: 64,
    coords: { lat: -26.1093, lng: 28.0500 },
    images: ['https://images.unsplash.com/photo-1568322445389-f64b0f5d4e91?w=400'],
  },
];

export const ADMIN_COLLECTION_POINTS = [
  {
    id: 'cp-1',
    name: 'Library Bistro Pickup Counter',
    buildingId: 'b-north-library',
    buildingName: 'Library',
    siteName: 'Merchant Place · North Campus',
    isExpress: true,
    isActive: true,
    ordersToday: 184,
    avgPickupMins: 4,
    instructions: 'Express pickup directly opposite the library entrance. Tap the QR code on the reader; staff will hand over your order.',
  },
  {
    id: 'cp-2',
    name: 'Library Express Kiosk',
    buildingId: 'b-north-library',
    buildingName: 'Library',
    siteName: 'Merchant Place · North Campus',
    isExpress: true,
    isActive: true,
    ordersToday: 80,
    avgPickupMins: 3,
    instructions: 'Self-service locker behind the lobby. Enter the last 4 of your reference.',
  },
  {
    id: 'cp-3',
    name: 'Library Catering Counter',
    buildingId: 'b-north-library',
    buildingName: 'Library',
    siteName: 'Merchant Place · North Campus',
    isExpress: false,
    isActive: true,
    ordersToday: 12,
    avgPickupMins: 8,
    instructions: 'For corporate / catering orders only. Confirm with the front desk on arrival.',
  },
  {
    id: 'cp-4',
    name: 'Atrium – Counter A',
    buildingId: 'b-main-atrium',
    buildingName: 'Atrium',
    siteName: 'Merchant Place · Main',
    isExpress: true,
    isActive: true,
    ordersToday: 168,
    avgPickupMins: 5,
    instructions: 'Pickup next to the espresso bar. Look for the order # on the screen.',
  },
  {
    id: 'cp-5',
    name: 'Atrium – Counter B',
    buildingId: 'b-main-atrium',
    buildingName: 'Atrium',
    siteName: 'Merchant Place · Main',
    isExpress: true,
    isActive: true,
    ordersToday: 80,
    avgPickupMins: 5,
    instructions: 'Secondary counter for batched pickup waves (12:00 – 14:00).',
  },
  {
    id: 'cp-6',
    name: 'Central Hall Pickup',
    buildingId: 'b-main-central',
    buildingName: 'Central Tower',
    siteName: 'Merchant Place · Main',
    isExpress: true,
    isActive: true,
    ordersToday: 184,
    avgPickupMins: 6,
    instructions: 'Show your QR at the security turnstile — collection is logged automatically.',
  },
  {
    id: 'cp-7',
    name: 'Courtyard Outdoor',
    buildingId: 'b-main-courtyard',
    buildingName: 'Courtyard',
    siteName: 'Merchant Place · Main',
    isExpress: true,
    isActive: true,
    ordersToday: 88,
    avgPickupMins: 7,
    instructions: 'Outdoor pickup window. Order # called out at the speaker.',
  },
  {
    id: 'cp-8',
    name: 'East Pavilion Qwik',
    buildingId: 'b-main-east',
    buildingName: 'East Pavilion',
    siteName: 'Merchant Place · Main',
    isExpress: true,
    isActive: false,
    ordersToday: 0,
    avgPickupMins: null,
    instructions: 'Temporarily closed for renovation. Reopening Q1 2027.',
  },
  {
    id: 'cp-9',
    name: 'Science Snack Bar',
    buildingId: 'b-north-science',
    buildingName: 'Science Building',
    siteName: 'Merchant Place · North Campus',
    isExpress: true,
    isActive: true,
    ordersToday: 92,
    avgPickupMins: 5,
    instructions: 'Counter inside the snack bar. Present your QR.',
  },
  {
    id: 'cp-10',
    name: 'Science Lab Express',
    buildingId: 'b-north-science',
    buildingName: 'Science Building',
    siteName: 'Merchant Place · North Campus',
    isExpress: true,
    isActive: true,
    ordersToday: 56,
    avgPickupMins: 4,
    instructions: 'Locker bank outside Lab 3B. Enter the last 4 of your reference.',
  },
  {
    id: 'cp-11',
    name: 'Residence Court Pickup',
    buildingId: 'b-south-res',
    buildingName: 'Residence Court',
    siteName: 'Merchant Place · South Residence',
    isExpress: true,
    isActive: true,
    ordersToday: 134,
    avgPickupMins: 6,
    instructions: 'Counter at the residence lobby. Student card or QR accepted.',
  },
  {
    id: 'cp-12',
    name: 'Eastgate Concourse',
    buildingId: 'b-south-eastgate',
    buildingName: 'Eastgate Concourse',
    siteName: 'Merchant Place · South Residence',
    isExpress: true,
    isActive: true,
    ordersToday: 64,
    avgPickupMins: 5,
    instructions: 'Pickup point beside the gate. Open 11:00 – 22:00.',
  },
];

export const REPORT_TYPES = [
  { id: 'sales', label: 'Sales', icon: 'IconReceipt' },
  { id: 'vendors', label: 'Vendor performance', icon: 'IconBuildingStore' },
  { id: 'demand', label: 'Demand & wastage', icon: 'IconChartLine' },
  { id: 'peak', label: 'Peak times', icon: 'IconClock' },
  { id: 'corporate', label: 'Corporate', icon: 'IconBriefcase' },
];

export const REPORT_RANGES = [
  { id: '7d', label: 'Last 7 days' },
  { id: '30d', label: 'Last 30 days' },
  { id: '90d', label: 'Quarter' },
  { id: 'ytd', label: 'Year to date' },
];

export const SALES_REPORT = {
  summary: {
    revenue: 1284260,
    orders: 38426,
    avgBasket: 33.42,
    newCustomers: 184,
    revenueDelta: '+12.4%',
    ordersDelta: '+8.6%',
    basketDelta: '+3.2%',
    customerDelta: '+22%',
  },
  revenueTrend: [
    { date: '25 Aug', revenue: 38400, orders: 920 },
    { date: '26 Aug', revenue: 41200, orders: 1050 },
    { date: '27 Aug', revenue: 44900, orders: 1180 },
    { date: '28 Aug', revenue: 49200, orders: 1320 },
    { date: '29 Aug', revenue: 42600, orders: 1180 },
    { date: '30 Aug', revenue: 38100, orders: 990 },
    { date: '31 Aug', revenue: 35200, orders: 880 },
    { date: '01 Sep', revenue: 48260, orders: 1284 },
  ],
  byPaymentMethod: [
    { name: 'Bank Card', value: 642180, percent: 50, color: '#0A8CFF' },
    { name: 'Digital Wallet', value: 384240, percent: 30, color: '#22A559' },
    { name: 'Cost Centre', value: 192640, percent: 15, color: '#D99A00' },
    { name: 'Employee Subsidy', value: 65200, percent: 5, color: '#D94A4A' },
  ],
  bySite: [
    { id: 'site-main', name: 'Merchant Place · Main', orders: 16280, revenue: 524180, share: 41 },
    { id: 'site-north', name: 'Merchant Place · North Campus', orders: 13420, revenue: 458420, share: 36 },
    { id: 'site-south', name: 'Merchant Place · South Residence', orders: 8726, revenue: 301660, share: 23 },
  ],
  byCategory: [
    { name: 'Lunch', orders: 14180, revenue: 482140, percent: 38 },
    { name: 'Breakfast', orders: 9420, revenue: 234180, percent: 18 },
    { name: 'Drinks', orders: 7240, revenue: 168420, percent: 13 },
    { name: 'Snacks', orders: 4180, revenue: 124800, percent: 10 },
    { name: 'Meals', orders: 3406, revenue: 274720, percent: 21 },
  ],
};

export const VENDOR_PERFORMANCE_REPORT = {
  summary: {
    topRevenue: 198420,
    topOrders: 224,
    avgPrep: '13.4 min',
    avgRating: 4.6,
  },
  rankings: [
    { rank: 1, name: 'Library Bistro', orders: 224, revenue: 198420, avgRating: 4.8, completionRate: 98, avgPrepMins: 11.2 },
    { rank: 2, name: 'Main Campus Cafe', orders: 198, revenue: 184260, avgRating: 4.6, completionRate: 96, avgPrepMins: 12.4 },
    { rank: 3, name: 'Dining Hall Central', orders: 176, revenue: 152930, avgRating: 4.6, completionRate: 97, avgPrepMins: 14.1 },
    { rank: 4, name: 'Grill House Court', orders: 152, revenue: 141890, avgRating: 4.5, completionRate: 94, avgPrepMins: 13.8 },
    { rank: 5, name: 'Residence Court Kitchen', orders: 134, revenue: 122480, avgRating: 4.7, completionRate: 92, avgPrepMins: 15.2 },
    { rank: 6, name: 'Science Snack Bar', orders: 78, revenue: 78430, avgRating: 4.4, completionRate: 90, avgPrepMins: 10.4 },
  ],
  topItems: [
    { name: 'Chicken Wrap & Salad', orders: 142, revenue: 6390, vendor: 'Library Bistro' },
    { name: 'House Cappuccino', orders: 124, revenue: 3720, vendor: 'Library Bistro' },
    { name: 'Grilled Chicken & Rice', orders: 96, revenue: 4704, vendor: 'Main Campus Cafe' },
    { name: 'Vegetable Pasta', orders: 88, revenue: 3520, vendor: 'Dining Hall Central' },
    { name: 'Berry Scone', orders: 76, revenue: 2128, vendor: 'Library Bistro' },
  ],
  cancellations: [
    { vendor: 'Grill House Court', cancellations: 18, refunds: 14, revenueLost: 1840 },
    { vendor: 'Library Bistro', cancellations: 12, refunds: 8, revenueLost: 1240 },
    { vendor: 'Dining Hall Central', cancellations: 8, refunds: 4, revenueLost: 720 },
    { vendor: 'Residence Court Kitchen', cancellations: 4, refunds: 2, revenueLost: 320 },
  ],
};

export const DEMAND_REPORT = {
  plannedVsActual: {
    planned: 42000,
    ordered: 38426,
    produced: 40000,
    unsold: 1574,
    wasted: 1240,
    wasteRate: 3.1,
  },
  trend: [
    { week: 'W1', planned: 9800, ordered: 9200, produced: 9600, wasted: 320, wasteRate: 3.4 },
    { week: 'W2', planned: 10200, ordered: 9800, produced: 10000, wasted: 280, wasteRate: 2.8 },
    { week: 'W3', planned: 10800, ordered: 10420, produced: 10800, wasted: 320, wasteRate: 3.0 },
    { week: 'W4', planned: 11200, ordered: 9006, produced: 9600, wasted: 320, wasteRate: 3.4 },
  ],
  byMeal: [
    { meal: 'Chicken Wrap & Salad', planned: 4200, ordered: 4142, produced: 4400, wasted: 220 },
    { meal: 'House Cappuccino', planned: 4800, ordered: 4628, produced: 4800, wasted: 120 },
    { meal: 'Grilled Chicken & Rice', planned: 3600, ordered: 3498, produced: 3600, wasted: 80 },
    { meal: 'Vegetable Pasta', planned: 2800, ordered: 2714, produced: 2800, wasted: 60 },
    { meal: 'Berry Scone', planned: 2400, ordered: 2280, produced: 2400, wasted: 100 },
  ],
};

export const PEAK_REPORT = {
  byHour: [
    { hour: '08:00', orders: 38 },
    { hour: '09:00', orders: 96 },
    { hour: '10:00', orders: 122 },
    { hour: '11:00', orders: 184 },
    { hour: '12:00', orders: 312 },
    { hour: '13:00', orders: 386 },
    { hour: '14:00', orders: 168 },
    { hour: '15:00', orders: 92 },
    { hour: '16:00', orders: 64 },
    { hour: '17:00', orders: 38 },
    { hour: '18:00', orders: 22 },
  ],
  byDayOfWeek: [
    { day: 'Mon', orders: 542 },
    { day: 'Tue', orders: 612 },
    { day: 'Wed', orders: 658 },
    { day: 'Thu', orders: 728 },
    { day: 'Fri', orders: 612 },
    { day: 'Sat', orders: 280 },
    { day: 'Sun', orders: 142 },
  ],
  heatmap: (() => {
    const days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
    const hours = ['08', '09', '10', '11', '12', '13', '14', '15', '16', '17'];
    const out = [];
    for (const d of days) {
      for (const h of hours) {
        const basePeak = (h === '12' || h === '13') ? 80 : 30;
        const dowBoost = (d === 'Wed' || d === 'Thu') ? 22 : 8;
        const isWeekend = (d === 'Sat' || d === 'Sun');
        const v = (isWeekend ? 10 : basePeak + dowBoost) + Math.floor(Math.random() * 18);
        out.push({ day: d, hour: h, value: v });
      }
    }
    return out;
  })(),
};

export const CORPORATE_REPORT = {
  summary: {
    orders: 84,
    revenue: 268420,
    avgOrder: 3195,
    growth: '+18.2%',
  },
  byCostCentre: [
    { code: 'EXEC-MD', name: 'Executive Office', orders: 18, revenue: 78420 },
    { code: 'HR-OPS', name: 'HR Operations', orders: 24, revenue: 68240 },
    { code: 'TECH-DEV', name: 'Engineering', orders: 16, revenue: 54180 },
    { code: 'FIN-CTRL', name: 'Finance', orders: 12, revenue: 38420 },
    { code: 'MKT-CAMP', name: 'Marketing', orders: 14, revenue: 29160 },
  ],
  byVendor: [
    { vendor: 'Main Campus Cafe', orders: 38, revenue: 124800 },
    { vendor: 'Library Bistro', orders: 28, revenue: 92420 },
    { vendor: 'Dining Hall Central', orders: 12, revenue: 38120 },
    { vendor: 'Grill House Court', orders: 6, revenue: 13080 },
  ],
upcoming: [
    { id: 'co-1', event: 'Quarterly All-hands', when: 'Today · 15:00', attendees: 184, vendor: 'Main Campus Cafe', costCentre: 'EXEC-MD' },
    { id: 'co-2', event: 'Engineering Town Hall', when: 'Tomorrow · 12:00', attendees: 64, vendor: 'Library Bistro', costCentre: 'TECH-DEV' },
    { id: 'co-3', event: 'Board Catering', when: 'Fri · 13:00', attendees: 12, vendor: 'Dining Hall Central', costCentre: 'EXEC-MD' },
  ],
};

export const AUDIT_TABS = [
  { id: 'audit', label: 'Audit log', icon: 'IconShieldCheck' },
  { id: 'security', label: 'Security events', icon: 'IconLock' },
];

export const AUDIT_RESOURCE_TYPES = [
  { id: 'all', label: 'All resources' },
  { id: 'vendors', label: 'Vendors' },
  { id: 'users', label: 'Users' },
  { id: 'orders', label: 'Orders' },
  { id: 'cafeterias', label: 'Cafeterias' },
  { id: 'settings', label: 'Settings' },
];

export const AUDIT_ACTION_TYPES = [
  { id: 'all', label: 'All actions' },
  { id: 'create', label: 'Created', tone: 'success' },
  { id: 'update', label: 'Updated', tone: 'info' },
  { id: 'delete', label: 'Deleted', tone: 'error' },
  { id: 'approve', label: 'Approved', tone: 'success' },
  { id: 'reject', label: 'Rejected', tone: 'error' },
  { id: 'refund', label: 'Refunded', tone: 'warning' },
  { id: 'login', label: 'Signed in', tone: 'info' },
  { id: 'role', label: 'Role change', tone: 'warning' },
];

export const AUDIT_LOGS = [
  {
    id: 'a1',
    actor: 'Nomvula Dube',
    actorRole: 'admin',
    action: 'Approved vendor',
    actionType: 'approve',
    resource: 'Vendor',
    resourceName: 'Woolworths Food Stop',
    resourceId: 'woolworths-food-stop',
    detail: 'Activated the vendor and published the menu.',
    ip: '102.165.32.10',
    userAgent: 'Chrome 128 · macOS',
    timestamp: 'Today · 14:08:24',
    delta: { field: 'status', from: 'pending', to: 'active' },
  },
  {
    id: 'a2',
    actor: 'Lerato Khumalo',
    actorRole: 'vendor_manager',
    action: 'Updated menu',
    actionType: 'update',
    resource: 'Menu item',
    resourceName: 'Chicken Wrap & Salad',
    resourceId: 'menu-item-1',
    detail: 'Base price changed from R42.00 to R45.00.',
    ip: '197.96.142.18',
    userAgent: 'Chrome 128 · Windows',
    timestamp: 'Today · 13:54:11',
    delta: { field: 'base_price', from: 'R 42.00', to: 'R 45.00' },
  },
  {
    id: 'a3',
    actor: 'Karabo Nkosi',
    actorRole: 'employee',
    action: 'Placed order',
    actionType: 'create',
    resource: 'Order',
    resourceName: '#48201',
    resourceId: '48201',
    detail: 'Corporate order for 6 attendees. Cost-centre EXEC-MD.',
    ip: '102.165.32.42',
    userAgent: 'Mobile Safari · iOS 18',
    timestamp: 'Today · 13:48:02',
    delta: null,
  },
  {
    id: 'a4',
    actor: 'Thuli Mokoena',
    actorRole: 'support',
    action: 'Refunded order',
    actionType: 'refund',
    resource: 'Order',
    resourceName: '#48198',
    resourceId: '48198',
    detail: 'Customer requested cancellation due to long prep time.',
    ip: '102.165.32.99',
    userAgent: 'Chrome 128 · Windows',
    timestamp: 'Today · 12:36:48',
    delta: { field: 'refund_amount', from: '—', to: 'R 118.00' },
  },
  {
    id: 'a5',
    actor: 'System',
    actorRole: 'system',
    action: 'Failed payment flagged',
    actionType: 'update',
    resource: 'Order',
    resourceName: '#48204',
    resourceId: '48204',
    detail: 'Bank declined, retry suggested. Customer notified via email.',
    ip: '—',
    userAgent: 'System',
    timestamp: 'Today · 11:14:32',
    delta: { field: 'payment_status', from: 'pending', to: 'declined' },
  },
  {
    id: 'a6',
    actor: 'Nomvula Dube',
    actorRole: 'admin',
    action: 'Changed user role',
    actionType: 'role',
    resource: 'User',
    resourceName: 'Sipho Dlamini',
    resourceId: 'u6',
    detail: 'Granted vendor_staff role. Pending activation.',
    ip: '102.165.32.10',
    userAgent: 'Chrome 128 · macOS',
    timestamp: 'Yesterday · 17:42:11',
    delta: { field: 'roles', from: '—', to: 'vendor_staff' },
  },
  {
    id: 'a7',
    actor: 'Nomvula Dube',
    actorRole: 'admin',
    action: 'Created cafeteria',
    actionType: 'create',
    resource: 'Building',
    resourceName: 'Eastgate Concourse',
    resourceId: 'b-south-eastgate',
    detail: 'New building registered under Merchant Place · South Residence.',
    ip: '102.165.32.10',
    userAgent: 'Chrome 128 · macOS',
    timestamp: 'Yesterday · 16:18:22',
    delta: null,
  },
  {
    id: 'a8',
    actor: 'System',
    actorRole: 'system',
    action: 'Cancelled expired cart',
    actionType: 'delete',
    resource: 'Cart',
    resourceName: 'cart-78',
    resourceId: 'cart-78',
    detail: 'Cart expired after 2 hours without checkout.',
    ip: '—',
    userAgent: 'Cron',
    timestamp: 'Yesterday · 16:02:00',
    delta: null,
  },
  {
    id: 'a9',
    actor: 'Thuli Mokoena',
    actorRole: 'support',
    action: 'Updated platform settings',
    actionType: 'update',
    resource: 'Settings',
    resourceName: 'Cancellation cutoff',
    resourceId: 'cancellation_rules',
    detail: 'Reduced cutoff window from 15 to 10 minutes for late lunch slots.',
    ip: '102.165.32.99',
    userAgent: 'Chrome 128 · Windows',
    timestamp: 'Yesterday · 14:50:14',
    delta: { field: 'cutoff_minutes', from: '15', to: '10' },
  },
  {
    id: 'a10',
    actor: 'Thabo Mokoena',
    actorRole: 'employee',
    action: 'Updated profile',
    actionType: 'update',
    resource: 'Profile',
    resourceName: 'Thabo Mokoena',
    resourceId: 'u1',
    detail: 'Changed dietary preference to include Halaal.',
    ip: '102.165.32.55',
    userAgent: 'Mobile Safari · iOS 18',
    timestamp: 'Yesterday · 11:14:00',
    delta: { field: 'dietary_tags', from: '[]', to: '["Halal"]' },
  },
  {
    id: 'a11',
    actor: 'Nomvula Dube',
    actorRole: 'admin',
    action: 'Deactivated vendor',
    actionType: 'reject',
    resource: 'Vendor',
    resourceName: 'Science Snack Bar',
    resourceId: 'science-snack-bar',
    detail: 'Vendor temporarily disabled pending inspection follow-up.',
    ip: '102.165.32.10',
    userAgent: 'Chrome 128 · macOS',
    timestamp: 'Yesterday · 09:12:48',
    delta: { field: 'status', from: 'active', to: 'inactive' },
  },
  {
    id: 'a12',
    actor: 'System',
    actorRole: 'system',
    action: 'Daily settlement exported',
    actionType: 'create',
    resource: 'Settlement',
    resourceName: 'SET-2026-08-30',
    resourceId: 'SET-2026-08-30',
    detail: 'Generated vendor settlement report. Distributed to finance@merchantmunnies.local.',
    ip: '—',
    userAgent: 'Cron',
    timestamp: '2 days ago · 02:00:14',
    delta: null,
  },
  {
    id: 'a13',
    actor: 'Ayanda Sithole',
    actorRole: 'finance',
    action: 'Exported refund report',
    actionType: 'create',
    resource: 'Report',
    resourceName: 'refunds_august_2026.csv',
    resourceId: 'rpt-318',
    detail: 'CSV covering 84 refunds across 12 vendors for finance review.',
    ip: '102.165.32.74',
    userAgent: 'Edge 127 · Windows',
    timestamp: '2 days ago · 11:32:18',
    delta: null,
  },
];

export const SECURITY_EVENTS = [
  {
    id: 's1',
    user: 'user@merchantmunnies.local',
    eventType: 'Suspicious sign-in attempt',
    success: false,
    severity: 'high',
    ip: '41.215.18.99',
    userAgent: 'HeadlessChrome · Unknown',
    location: 'Frankfurt, DE',
    timestamp: 'Today · 14:12:08',
    detail: 'Multiple rapid failed logins from unfamiliar IP and user-agent.',
    actionTaken: 'Account temporarily locked. Email dispatched to user.',
  },
  {
    id: 's2',
    user: 'Nomvula Dube',
    eventType: 'Password changed',
    success: true,
    severity: 'info',
    ip: '102.165.32.10',
    userAgent: 'Chrome 128 · macOS',
    location: 'Johannesburg, ZA',
    timestamp: 'Today · 09:54:42',
    detail: 'Self-service password update.',
    actionTaken: 'Sessions revoked across devices.',
  },
  {
    id: 's3',
    user: 'Karabo Nkosi',
    eventType: 'MFA challenge',
    success: true,
    severity: 'info',
    ip: '102.165.32.42',
    userAgent: 'Mobile Safari · iOS 18',
    location: 'Johannesburg, ZA',
    timestamp: 'Today · 08:32:11',
    detail: 'Authenticator app verification successful.',
    actionTaken: null,
  },
  {
    id: 's4',
    user: 'thuli@librarybistro.local',
    eventType: 'API rate-limited',
    success: false,
    severity: 'warning',
    ip: '197.96.142.18',
    userAgent: 'curl/8.4.0',
    location: 'Cape Town, ZA',
    timestamp: 'Yesterday · 22:18:04',
    detail: 'Automated scanner exceeded 600 requests/min from a single IP.',
    actionTaken: 'Temporarily throttled. Vendor support notified.',
  },
  {
    id: 's5',
    user: 'Nomvula Dube',
    eventType: 'Admin role escalated',
    success: true,
    severity: 'info',
    ip: '102.165.32.10',
    userAgent: 'Chrome 128 · macOS',
    location: 'Johannesburg, ZA',
    timestamp: 'Yesterday · 15:02:50',
    detail: 'Granted `finance` role to support team for incident triage.',
    actionTaken: 'Audit trail updated. MFA required on next login.',
  },
  {
    id: 's6',
    user: 'unk@unknown-origin.local',
    eventType: 'Brute force pattern',
    success: false,
    severity: 'critical',
    ip: '45.33.32.156',
    userAgent: 'Unknown · Linux',
    location: 'San Francisco, US',
    timestamp: 'Yesterday · 03:18:21',
    detail: '2 600+ authentication attempts in 10 minutes from non-existent user.',
    actionTaken: 'IP permanently blacklisted. SOC notified.',
  },
  {
    id: 's7',
    user: 'Ayanda Sithole',
    eventType: 'New device signed in',
    success: true,
    severity: 'warning',
    ip: '102.165.32.74',
    userAgent: 'Edge 127 · Windows',
    location: 'Johannesburg, ZA',
    timestamp: 'Yesterday · 13:30:01',
    detail: 'Sign-in on a new browser/device.',
    actionTaken: 'Email confirmation dispatched to the user.',
  },
  {
    id: 's8',
    user: 'Mpho Sithole',
    eventType: 'Token revoked',
    success: true,
    severity: 'info',
    ip: '102.165.32.20',
    userAgent: 'Chrome 124 · Android',
    location: 'Pretoria, ZA',
    timestamp: '2 days ago · 14:18:55',
    detail: 'User signed out from all devices after inactivity.',
    actionTaken: null,
  },
];

export const AUDIT_SUMMARY = {
  totalEvents: 1248,
  today: 318,
  criticalAlerts: 3,
  uniqueActors: 84,
  resourceChanges: 412,
  failedSignIns: 7,
  retentionDays: 365,
};

export const COMPLAINT_STATUSES = [
  { id: 'open', label: 'Open', tone: 'warning' },
  { id: 'assigned', label: 'Assigned', tone: 'info' },
  { id: 'in_review', label: 'In review', tone: 'info' },
  { id: 'resolved', label: 'Resolved', tone: 'success' },
  { id: 'closed', label: 'Closed', tone: 'success' },
  { id: 'rejected', label: 'Rejected', tone: 'error' },
];

export const COMPLAINT_TABS = [
  { id: 'open', label: 'Open', tone: 'warning' },
  { id: 'in_progress', label: 'In progress', tone: 'info' },
  { id: 'resolved', label: 'Resolved', tone: 'success' },
];

export const COMPLAINT_CATEGORIES = [
  { id: 'cat-food-quality', label: 'Food quality' },
  { id: 'cat-order-issue', label: 'Order issue' },
  { id: 'cat-payment', label: 'Payment & refunds' },
  { id: 'cat-collection', label: 'Collection experience' },
  { id: 'cat-app-issue', label: 'App / technical' },
  { id: 'cat-account', label: 'Account & access' },
  { id: 'cat-vendor', label: 'Vendor behaviour' },
];

export const COMPLAINT_TEAM = [
  { id: 't-thuli', name: 'Thuli Mokoena', role: 'support', avatar: null },
  { id: 't-ayanda', name: 'Ayanda Sithole', role: 'support', avatar: null },
  { id: 't-jason', name: 'Jason Pillay', role: 'support', avatar: null },
];

export const COMPLAINTS_SUMMARY = {
  open: 14,
  inProgress: 22,
  resolved: 168,
  avgResolutionHours: 6.4,
  slaPercent: 92,
};

export const COMPLAINTS = [
  {
    id: 'cmp-2024-882',
    subject: 'Wrong order delivered — order #48201',
    description: 'I received a Beef Burger instead of the Grilled Chicken Wrap I ordered at Main Campus Cafe. The cashier only confirmed visually but no one read back the order. Please refund.',
    category: 'cat-order-issue',
    categoryLabel: 'Order issue',
    priority: 'high',
    status: 'open',
    user: 'Karabo Nkosi',
    userNumber: 'EMP-10062',
    vendor: 'Main Campus Cafe',
    vendorId: 'main-campus-cafe',
    order: '#48201',
    submitted: 'Today · 11:48',
    rating: { overall: 2, food: 4, prep: 3, collection: 2, service: 1 },
    assignedTo: null,
    sla: '4 hr · at risk',
  },
  {
    id: 'cmp-2024-881',
    subject: 'Allergen advice was incorrect',
    description: 'I told the vendor I am gluten-sensitive. The menu shows gluten-conscious but the wrap clearly contained gluten. I had to rush for medication.',
    category: 'cat-food-quality',
    categoryLabel: 'Food quality',
    priority: 'urgent',
    status: 'assigned',
    user: 'Naledi Botha',
    userNumber: 'EMP-10045',
    vendor: 'Library Bistro',
    vendorId: 'library-bistro',
    order: '#48174',
    submitted: 'Today · 09:32',
    rating: { overall: 1, food: 1, prep: 3, collection: 4, service: 3 },
    assignedTo: 'Thuli Mokoena',
    sla: '2 hr · breached',
  },
  {
    id: 'cmp-2024-880',
    subject: 'Refund not received after 5 days',
    description: 'Order #48198 was rejected by the vendor and refund was approved the same day but I still see the charge on my card. Can you confirm timeline?',
    category: 'cat-payment',
    categoryLabel: 'Payment & refunds',
    priority: 'medium',
    status: 'in_review',
    user: 'Mpho Sithole',
    userNumber: 'EMP-10082',
    vendor: 'Library Bistro',
    vendorId: 'library-bistro',
    order: '#48198',
    submitted: 'Yesterday · 14:02',
    rating: { overall: 2, food: 4, prep: 4, collection: 4, service: 2 },
    assignedTo: 'Ayanda Sithole',
    sla: '12 hr · on track',
  },
  {
    id: 'cmp-2024-879',
    subject: 'Vendor rude during pickup',
    description: 'Staff member at Grill House picked up my order but threw the bag on the counter when I asked about the sauce. Very off-putting.',
    category: 'cat-vendor',
    categoryLabel: 'Vendor behaviour',
    priority: 'medium',
    status: 'in_review',
    user: 'Sipho Dlamini',
    userNumber: 'VND-00022',
    vendor: 'Grill House Court',
    vendorId: 'grill-house-court',
    order: '#48199',
    submitted: 'Yesterday · 11:14',
    rating: { overall: 2, food: 4, prep: 4, collection: 3, service: 1 },
    assignedTo: 'Jason Pillay',
    sla: '12 hr · on track',
  },
  {
    id: 'cmp-2024-877',
    subject: 'Collection point confused me',
    description: 'There were no signage at the East Pavilion counter, and I had to walk around. The instructions in the app said counter A but I went to counter B.',
    category: 'cat-collection',
    categoryLabel: 'Collection experience',
    priority: 'low',
    status: 'in_review',
    user: 'Thabo Mokoena',
    userNumber: 'EMP-10234',
    vendor: 'Main Campus Cafe',
    vendorId: 'main-campus-cafe',
    order: '#48194',
    submitted: 'Yesterday · 09:54',
    rating: { overall: 3, food: 4, prep: 5, collection: 2, service: 4 },
    assignedTo: 'Thuli Mokoena',
    sla: '24 hr · on track',
  },
  {
    id: 'cmp-2024-873',
    subject: 'App kept crashing after update',
    description: 'After the iOS update last week, the cart would not save my collection slot. Had to call support to place the order.',
    category: 'cat-app-issue',
    categoryLabel: 'App / technical',
    priority: 'medium',
    status: 'resolved',
    user: 'Nomvula Dube',
    userNumber: 'ADM-00001',
    vendor: 'Library Bistro',
    vendorId: 'library-bistro',
    order: null,
    submitted: '2 days ago',
    rating: { overall: 3, food: null, prep: null, collection: 4, service: null },
    assignedTo: 'Ayanda Sithole',
    sla: 'Closed',
    resolution: 'Root cause: slot persistence service was failing on iOS 18.4. Hotfix deployed (v3.8.2). User confirmed working.',
    resolvedAt: 'Yesterday · 16:20',
  },
  {
    id: 'cmp-2024-870',
    subject: 'Refund issued, collection not loggable',
    description: 'Got my refund for #48174 but I also tried to mark the order as collected in the app and the button was greyed out.',
    category: 'cat-app-issue',
    categoryLabel: 'App / technical',
    priority: 'low',
    status: 'resolved',
    user: 'Karabo Nkosi',
    userNumber: 'EMP-10062',
    vendor: 'Library Bistro',
    vendorId: 'library-bistro',
    order: '#48174',
    submitted: '3 days ago',
    rating: null,
    assignedTo: 'Jason Pillay',
    sla: 'Closed',
    resolution: 'Refund cancelled order cannot be marked collected. UX guard added so the button shows the explanation instead of being disabled.',
    resolvedAt: '2 days ago · 10:14',
  },
  {
    id: 'cmp-2024-869',
    subject: 'Collection counter was closed at noon',
    description: 'Arrived at the counter at 12:05 but the vendor said their hours had changed. The app still showed them open.',
    category: 'cat-vendor',
    categoryLabel: 'Vendor behaviour',
    priority: 'high',
    status: 'resolved',
    user: 'Nompilo Cele',
    userNumber: 'EMP-10155',
    vendor: 'Residence Court Kitchen',
    vendorId: 'res-court-kitchen',
    order: '#48192',
    submitted: '3 days ago',
    rating: { overall: 2, food: 4, prep: 5, collection: 1, service: 3 },
    assignedTo: 'Thuli Mokoena',
    sla: 'Closed',
    resolution: 'Operating hours were updated by the vendor without notice. Vendor reminded of SLA. Picking up cancelled, refund issued.',
    resolvedAt: 'Yesterday · 08:00',
  },
];

export const COMPLAINT_MESSAGES = [
  {
    id: 'm1',
    sender: 'Karabo Nkosi (employee)',
    role: 'customer',
    time: 'Today · 11:48',
    body: 'I ordered a Grilled Chicken Wrap and got a Beef Burger. Please refund — I have not touched the burger.',
    tone: 'info',
  },
  {
    id: 'm2',
    sender: 'Thuli Mokoena (support)',
    role: 'support',
    time: 'Today · 11:55',
    body: 'Hi Karabo — thanks for flagging. Can you confirm the order number on the receipt was #48201? Asking the vendor to verify before issuing the refund.',
    tone: 'support',
  },
  {
    id: 'm3',
    sender: 'Karabo Nkosi (employee)',
    role: 'customer',
    time: 'Today · 12:02',
    body: 'Confirmed, #48201. Photo of receipt attached.',
    tone: 'info',
  },
  {
    id: 'm4',
    sender: 'Thuli Mokoena (support)',
    role: 'support',
    time: 'Today · 12:08',
    body: 'Vendor confirmed the wrap was mispacked. Refund of R215.00 initiated — should land in your account within 2 working days.',
    tone: 'support',
  },
];

export const COMPLAINT_ACTIVITY = [
  { id: 'a1', at: 'Today · 11:48', actor: 'Karabo Nkosi', action: 'Submitted complaint', tone: 'info' },
  { id: 'a2', at: 'Today · 11:55', actor: 'System', action: 'Routed to order #48201, vendor Main Campus Cafe', tone: 'info' },
  { id: 'a3', at: 'Today · 12:08', actor: 'Thuli Mokoena', action: 'Refund of R 215.00 initiated', tone: 'success' },
  { id: 'a4', at: 'Today · 12:18', actor: 'System', action: 'SLA breached 1 hr — escalated', tone: 'warning' },
];

export const COMPLAINT_METRICS = {
  byCategory: [
    { name: 'Order issue', count: 42, percent: 38 },
    { name: 'Food quality', count: 28, percent: 25 },
    { name: 'Payment & refunds', count: 18, percent: 16 },
    { name: 'Collection experience', count: 12, percent: 11 },
    { name: 'Vendor behaviour', count: 6, percent: 5 },
    { name: 'App / technical', count: 4, percent: 4 },
    { name: 'Account', count: 2, percent: 1 },
  ],
};

export const ANNOUNCEMENT_TABS = [
  { id: 'active', label: 'Active', tone: 'success' },
  { id: 'scheduled', label: 'Scheduled', tone: 'info' },
  { id: 'draft', label: 'Drafts', tone: 'warning' },
  { id: 'archived', label: 'Archived', tone: 'info' },
];

export const ANNOUNCEMENT_CATEGORIES = [
  { id: 'ops', label: 'Operations' },
  { id: 'promo', label: 'Promotion' },
  { id: 'maintenance', label: 'Maintenance' },
  { id: 'compliance', label: 'Compliance' },
  { id: 'corporate', label: 'Corporate event' },
];

export const ANNOUNCEMENT_CHANNELS = [
  { id: 'in_app', label: 'In-app banner' },
  { id: 'push', label: 'Push notification' },
  { id: 'email', label: 'Email' },
];

export const ANNOUNCEMENT_SUMMARY = {
  active: 4,
  reaching: 18642,
  scheduledThisWeek: 2,
  openRate: 76,
  draftPending: 3,
};

export const ANNOUNCEMENTS = [
  {
    id: 'ann-2026-018',
    title: 'New vendor onboarded — Woolworths Food Stop',
    body: 'Woolworths Food Stop is live at Merchant Place · South Residence starting Monday. Look for pre-packed salads, wraps and grilled protein bowls across the lunch window.',
    category: 'ops',
    categoryLabel: 'Operations',
    severity: 'info',
    channels: ['in_app', 'push'],
    audienceRoles: ['employee', 'executive_assistant', 'event_organiser'],
    audienceSites: ['site-south'],
    audienceSitesNames: ['Merchant Place · South Residence'],
    status: 'active',
    startsAt: '2026-09-01 · 09:00',
    endsAt: '2026-09-08 · 18:00',
    createdBy: 'Nomvula Dube',
    createdAt: '2026-08-31 · 11:20',
    reach: {
      targeted: 1840,
      delivered: 1840,
      opened: 1280,
      clicked: 412,
      dismissed: 22,
    },
  },
  {
    id: 'ann-2026-017',
    title: 'Lunch rush capped to 12:00 – 13:30 across the North campus',
    body: 'To keep queue times tight during peak, we are temporarily capping new order acceptance between 12:00 and 13:30 to allow vendors to fulfil existing baskets. Collection remains open all day.',
    category: 'maintenance',
    categoryLabel: 'Maintenance',
    severity: 'warning',
    channels: ['in_app', 'email'],
    audienceRoles: ['employee', 'executive_assistant', 'event_organiser'],
    audienceSites: ['site-north'],
    audienceSitesNames: ['Merchant Place · North Campus'],
    status: 'active',
    startsAt: '2026-08-31 · 07:30',
    endsAt: '2026-09-14 · 17:00',
    createdBy: 'Nomvula Dube',
    createdAt: '2026-08-30 · 14:55',
    reach: {
      targeted: 4620,
      delivered: 4620,
      opened: 3948,
      clicked: 612,
      dismissed: 18,
    },
  },
  {
    id: 'ann-2026-016',
    title: 'Special: 20% off house coffee at Library Bistro until Friday',
    body: 'From now until Friday, ask for the “MM20” tag at Library Bistro to enjoy 20% off any house-blend coffee. Limited to two per employee.',
    category: 'promo',
    categoryLabel: 'Promotion',
    severity: 'success',
    channels: ['in_app', 'push', 'email'],
    audienceRoles: ['employee'],
    audienceSites: ['site-main', 'site-north'],
    audienceSitesNames: ['Merchant Place · Main', 'Merchant Place · North Campus'],
    status: 'active',
    startsAt: '2026-08-28 · 08:00',
    endsAt: '2026-09-04 · 17:00',
    createdBy: 'Marketing',
    createdAt: '2026-08-27 · 16:14',
    reach: {
      targeted: 8420,
      delivered: 8420,
      opened: 6218,
      clicked: 1842,
      dismissed: 8,
    },
  },
  {
    id: 'ann-2026-015',
    title: 'Reminder: POPIA consent now required for new accounts',
    body: 'All new profiles created after 1 September must accept the updated POPIA privacy notice before placing orders. Update your consent any time in Profile → Preferences.',
    category: 'compliance',
    categoryLabel: 'Compliance',
    severity: 'info',
    channels: ['in_app', 'email'],
    audienceRoles: ['employee', 'executive_assistant', 'event_organiser'],
    audienceSites: null,
    audienceSitesNames: ['All campuses'],
    status: 'active',
    startsAt: '2026-08-26 · 12:00',
    endsAt: 'Ongoing',
    createdBy: 'Compliance Team',
    createdAt: '2026-08-24 · 09:00',
    reach: {
      targeted: 11220,
      delivered: 11180,
      opened: 7462,
      clicked: 1924,
      dismissed: 184,
    },
  },
  {
    id: 'ann-2026-019',
    title: 'Saturday brunch service rolling out — North Campus',
    body: 'From Saturday 12 September, Library Bistro will open from 08:00 – 14:00 on weekends. Order slots open at 6 AM the previous morning.',
    category: 'ops',
    categoryLabel: 'Operations',
    severity: 'info',
    channels: ['in_app'],
    audienceRoles: ['employee', 'executive_assistant'],
    audienceSites: ['site-north'],
    audienceSitesNames: ['Merchant Place · North Campus'],
    status: 'scheduled',
    startsAt: '2026-09-08 · 06:00',
    endsAt: 'Ongoing',
    createdBy: 'Nomvula Dube',
    createdAt: 'Today · 10:18',
    reach: {
      targeted: 4620,
      delivered: 0,
      opened: 0,
      clicked: 0,
      dismissed: 0,
    },
  },
  {
    id: 'ann-2026-020',
    title: 'Quarterly all-hands catering — confirm attendance',
    body: 'Friday 12 September 14:00. Catered by Main Campus Cafe. RSVP before Wednesday so we can confirm dietary requirements.',
    category: 'corporate',
    categoryLabel: 'Corporate event',
    severity: 'info',
    channels: ['in_app', 'email', 'push'],
    audienceRoles: ['employee', 'executive_assistant'],
    audienceSites: ['site-main'],
    audienceSitesNames: ['Merchant Place · Main'],
    status: 'scheduled',
    startsAt: '2026-09-05 · 09:00',
    endsAt: '2026-09-12 · 14:00',
    createdBy: 'Executive Office',
    createdAt: 'Yesterday · 13:14',
    reach: {
      targeted: 186,
      delivered: 0,
      opened: 0,
      clicked: 0,
      dismissed: 0,
    },
  },
  {
    id: 'ann-2026-014',
    title: 'Tech maintenance window — Saturday 03:00 – 05:00',
    body: 'The merchant platform will be unavailable for a 30 minute window during our scheduled database maintenance. Any active orders will continue to be fulfilled.',
    category: 'maintenance',
    categoryLabel: 'Maintenance',
    severity: 'warning',
    channels: ['in_app', 'email'],
    audienceRoles: ['employee', 'vendor_staff', 'vendor_manager', 'admin'],
    audienceSites: null,
    audienceSitesNames: ['All campuses'],
    status: 'archived',
    startsAt: '2026-08-23 · 03:00',
    endsAt: '2026-08-23 · 05:00',
    createdBy: 'Ops Team',
    createdAt: '2026-08-22 · 11:48',
    archivedAt: '2026-08-23 · 06:00',
    reach: {
      targeted: 14380,
      delivered: 14380,
      opened: 11242,
      clicked: 618,
      dismissed: 412,
    },
  },
  {
    id: 'ann-2026-013',
    title: 'Pilot rollout — Save the date',
    body: 'Draft placeholder for the September pilot kickoff communication. Awaiting final sign-off from Operations and Brand.',
    category: 'ops',
    categoryLabel: 'Operations',
    severity: 'info',
    channels: ['in_app'],
    audienceRoles: ['employee'],
    audienceSites: null,
    audienceSitesNames: ['All campuses'],
    status: 'draft',
    startsAt: '2026-09-15 · 09:00',
    endsAt: '2026-09-22 · 17:00',
    createdBy: 'Nomvula Dube',
    createdAt: 'Yesterday · 17:14',
    reach: null,
  },
  {
    id: 'ann-2026-012',
    title: 'Vendor performance scorecards — coming Q1 2027',
    body: 'Draft placeholder. We are working on a public scorecard showing prep times, ratings, and waste. Vendor managers will get a private preview first.',
    category: 'ops',
    categoryLabel: 'Operations',
    severity: 'info',
    channels: ['in_app'],
    audienceRoles: ['vendor_manager'],
    audienceSites: null,
    audienceSitesNames: ['All campuses'],
    status: 'draft',
    startsAt: '2026-10-01 · 09:00',
    endsAt: 'Ongoing',
    createdBy: 'Karabo Nkosi',
    createdAt: '2 days ago',
    reach: null,
  },
];

export const ANNOUNCEMENT_TARGET_TEMPLATES = [
  {
    id: 'all-employees',
    label: 'All employees',
    icon: 'IconUsers',
    roles: ['employee', 'executive_assistant', 'event_organiser'],
    sites: null,
    sitesLabels: ['All campuses'],
    reach: 11220,
  },
  {
    id: 'main-employees',
    label: 'Main site employees',
    icon: 'IconBuilding',
    roles: ['employee'],
    sites: ['site-main'],
    sitesLabels: ['Merchant Place · Main'],
    reach: 4820,
  },
  {
    id: 'all-vendors',
    label: 'All vendors',
    icon: 'IconBuildingStore',
    roles: ['vendor_staff', 'vendor_manager'],
    sites: null,
    sitesLabels: ['All campuses'],
    reach: 84,
  },
  {
    id: 'finance-and-admin',
    label: 'Finance & admin',
    icon: 'IconShieldCheck',
    roles: ['finance', 'admin'],
    sites: null,
    sitesLabels: ['All campuses'],
    reach: 18,
  },
];

export const ANNOUNCEMENT_ACTIVITY = [
  { id: 'l1', at: 'Today · 09:00', actor: 'Nomvula Dube', action: 'Drafted announcement "Saturday brunch service rolling out"', tone: 'info' },
  { id: 'l2', at: 'Today · 10:18', actor: 'Nomvula Dube', action: 'Scheduled launch for 8 September 06:00', tone: 'info' },
  { id: 'l3', at: 'Yesterday · 17:14', actor: 'Karabo Nkosi', action: 'Created draft "Vendor performance scorecards"', tone: 'info' },
  { id: 'l4', at: 'Yesterday · 13:14', actor: 'Executive Office', action: 'Approved catering announcement for Friday event', tone: 'success' },
  { id: 'l5', at: '2 days ago · 16:14', actor: 'Marketing', action: 'Launched MM20 promo across Main + North', tone: 'success' },
  { id: 'l6', at: '2 days ago · 08:00', actor: 'Ops Team', action: 'Closed tech maintenance window', tone: 'info' },
];

export const SETTINGS_TABS = [
  { id: 'general', label: 'General', icon: 'IconSettings' },
  { id: 'fees', label: 'Fees & Tax', icon: 'IconCash' },
  { id: 'cancellations', label: 'Cancellations', icon: 'IconBan' },
  { id: 'features', label: 'Feature flags', icon: 'IconFlag' },
  { id: 'notifications', label: 'Notifications', icon: 'IconBell' },
  { id: 'maintenance', label: 'Maintenance', icon: 'IconTools' },
];

export const PLATFORM_SETTINGS = [
  { key: 'app.name', value: 'Merchant Munchies', description: 'Public-facing product name.', is_sensitive: false, updated_at: '2025-08-14 · 09:32' },
  { key: 'support.email', value: 'support@merchantmunnies.local', description: 'First-line support mailbox.', is_sensitive: false, updated_at: '2025-08-14 · 09:32' },
  { key: 'support.phone', value: '+27 11 555 0100', description: 'Piloted during launch week only.', is_sensitive: false, updated_at: '2025-08-14 · 09:32' },
  { key: 'ordering.default_timezone', value: 'Africa/Johannesburg', description: 'Applied to all collection slot calculations.', is_sensitive: false, updated_at: '2025-08-14 · 09:32' },
  { key: 'ordering.lead_time_min', value: 15, description: 'Min minutes between order time and earliest slot.', is_sensitive: false, updated_at: '2025-09-01 · 10:14' },
  { key: 'ordering.max_basket_items', value: 25, description: 'Per-cart cap.', is_sensitive: false, updated_at: '2025-09-01 · 10:14' },
  { key: 'security.mfa_required', value: true, description: 'Force MFA for all admin and finance users.', is_sensitive: false, updated_at: '2025-09-01 · 10:14' },
  { key: 'legal.popia_version', value: 'v3.2', description: 'Latest privacy notice timestamp.', is_sensitive: false, updated_at: '2025-09-01 · 10:14' },
];

export const FEE_RULES = [
  {
    id: 'fee-1',
    name: 'Platform service fee',
    scope: 'platform',
    scopeLabel: 'Platform-wide',
    site: null,
    siteLabel: '—',
    vendorLocation: null,
    vendorLocationLabel: '—',
    feeType: 'service_fee',
    calculationType: 'percentage',
    amount: 5,
    displayAmount: '5%',
    activeFrom: '2025-08-01',
    activeUntil: null,
    priority: 10,
    isActive: true,
    description: 'Default service charge applied to every order.',
  },
  {
    id: 'fee-2',
    name: 'Payment processing fee',
    scope: 'platform',
    scopeLabel: 'Platform-wide',
    site: null,
    siteLabel: '—',
    vendorLocation: null,
    vendorLocationLabel: '—',
    feeType: 'processing_fee',
    calculationType: 'percentage',
    amount: 2,
    displayAmount: '2%',
    activeFrom: '2025-08-01',
    activeUntil: null,
    priority: 20,
    isActive: true,
    description: 'Applied at the payment provider level on every transaction.',
  },
  {
    id: 'fee-3',
    name: 'North site delivery surcharge',
    scope: 'site',
    scopeLabel: 'Site',
    site: 'site-north',
    siteLabel: 'Merchant Place · North Campus',
    vendorLocation: null,
    vendorLocationLabel: '—',
    feeType: 'delivery_fee',
    calculationType: 'fixed',
    amount: 8,
    displayAmount: 'R 8.00',
    activeFrom: '2025-09-01',
    activeUntil: null,
    priority: 30,
    isActive: true,
    description: 'Flat delivery surcharge for North campus orders until courier capacity scales.',
  },
  {
    id: 'fee-4',
    name: 'Library Bistro weekend surcharge',
    scope: 'vendor_location',
    scopeLabel: 'Vendor location',
    site: 'site-north',
    siteLabel: 'Merchant Place · North Campus',
    vendorLocation: 'vl-library-bistro',
    vendorLocationLabel: 'Library Bistro',
    feeType: 'service_fee',
    calculationType: 'fixed',
    amount: 12,
    displayAmount: 'R 12.00',
    activeFrom: '2026-09-12',
    activeUntil: '2026-10-12',
    priority: 50,
    isActive: true,
    description: 'Pilot surcharge for the weekend brunch trial.',
  },
  {
    id: 'fee-5',
    name: 'Late pickup fee (legacy)',
    scope: 'platform',
    scopeLabel: 'Platform-wide',
    site: null,
    siteLabel: '—',
    vendorLocation: null,
    vendorLocationLabel: '—',
    feeType: 'service_fee',
    calculationType: 'fixed',
    amount: 25,
    displayAmount: 'R 25.00',
    activeFrom: '2024-04-01',
    activeUntil: '2025-12-31',
    priority: 80,
    isActive: false,
    description: 'Deprecated rule. Kept for audit reconciliation.',
  },
];

export const TAX_RATES = [
  {
    id: 'tax-1',
    name: 'VAT · Main campus',
    site: 'site-main',
    siteLabel: 'Merchant Place · Main',
    rate: 15,
    displayRate: '15%',
    activeFrom: '2025-04-01',
    activeUntil: null,
    isActive: true,
  },
  {
    id: 'tax-2',
    name: 'VAT · North campus',
    site: 'site-north',
    siteLabel: 'Merchant Place · North Campus',
    rate: 14,
    displayRate: '14%',
    activeFrom: '2025-04-01',
    activeUntil: null,
    isActive: true,
  },
  {
    id: 'tax-3',
    name: 'VAT · South residence',
    site: 'site-south',
    siteLabel: 'Merchant Place · South Residence',
    rate: 15,
    displayRate: '15%',
    activeFrom: '2025-04-01',
    activeUntil: null,
    isActive: true,
  },
];

export const CANCELLATION_RULES = [
  {
    id: 'cr-1',
    vendorLocation: 'Main Campus Cafe · Atrium',
    vendorLocationId: 'vl-main',
    cutoffMinutes: 15,
    allowAfterPayment: true,
    defaultRefundPercent: 100,
    adminOverrideAllowed: true,
    isActive: true,
    lastEditedBy: 'Nomvula Dube',
    lastEditedAt: '2 days ago',
    note: 'Default rule. Vendor confirms refunds up to 2 hours post-collection.',
  },
  {
    id: 'cr-2',
    vendorLocation: 'Library Bistro · Library level',
    vendorLocationId: 'vl-library-bistro',
    cutoffMinutes: 10,
    allowAfterPayment: true,
    defaultRefundPercent: 100,
    adminOverrideAllowed: true,
    isActive: true,
    lastEditedBy: 'Nomvula Dube',
    lastEditedAt: 'Yesterday · 14:50',
    note: 'Reduced from 15 → 10 min during peak lunch windows.',
  },
  {
    id: 'cr-3',
    vendorLocation: 'Grill House Court · Courtyard',
    vendorLocationId: 'vl-grill',
    cutoffMinutes: 20,
    allowAfterPayment: false,
    defaultRefundPercent: 50,
    adminOverrideAllowed: true,
    isActive: true,
    lastEditedBy: 'Thuli Mokoena',
    lastEditedAt: '1 week ago',
    note: 'Strict refund policy — vendor takes raw cost hit after 20 min.',
  },
  {
    id: 'cr-4',
    vendorLocation: 'Dining Hall Central',
    vendorLocationId: 'vl-dining',
    cutoffMinutes: 15,
    allowAfterPayment: true,
    defaultRefundPercent: 100,
    adminOverrideAllowed: false,
    isActive: true,
    lastEditedBy: 'Nomvula Dube',
    lastEditedAt: '3 weeks ago',
    note: 'Default rule. Vendor staff handle their own refunds.',
  },
];

export const FEATURE_FLAGS = [
  {
    key: 'flag-corporate-catering',
    name: 'Corporate catering',
    description: 'Enable catering requests, quotes, and approvals for executives and assistants.',
    enabled: true,
    scope: 'Platform',
    scopeDetail: 'All campuses',
    rolloutPercent: 100,
    lastToggledBy: 'Nomvula Dube',
    lastToggledAt: '2025-08-12 · 14:22',
    icon: 'IconBriefcase',
    tone: 'success',
  },
  {
    key: 'flag-express-pickup',
    name: 'Express pickup',
    description: 'Allow QR-only collection at counters tagged is_express.',
    enabled: true,
    scope: 'Platform',
    scopeDetail: 'All campuses',
    rolloutPercent: 100,
    lastToggledBy: 'Nomvula Dube',
    lastToggledAt: '2025-08-08 · 09:14',
    icon: 'IconBolt',
    tone: 'success',
  },
  {
    key: 'flag-subsidy-meals',
    name: 'Subsidy / meal benefits',
    description: 'Allow the company_subsidy and corporate_purchasing payment methods.',
    enabled: true,
    scope: 'Platform',
    scopeDetail: 'All campuses',
    rolloutPercent: 100,
    lastToggledBy: 'Nomvula Dube',
    lastToggledAt: '2025-09-01 · 08:42',
    icon: 'IconGift',
    tone: 'info',
  },
  {
    key: 'flag-weekend-service',
    name: 'Weekend service',
    description: 'Allow vendor operating hours to extend into Saturdays and Sundays.',
    enabled: false,
    scope: 'Site',
    scopeDetail: 'Merchant Place · North Campus',
    rolloutPercent: 0,
    lastToggledBy: 'Nomvula Dube',
    lastToggledAt: '2026-08-30 · 16:14',
    icon: 'IconCalendar',
    tone: 'warning',
  },
  {
    key: 'flag-pilot-corporate-sandton',
    name: 'Sandton pilot cohort',
    description: 'Opt-in for the Sandton pilot cohort. Only eligible accounts will see corporate catering.',
    enabled: false,
    scope: 'Site',
    scopeDetail: 'Merchant Place · Sandton (planned)',
    rolloutPercent: 25,
    lastToggledBy: 'Karabo Nkosi',
    lastToggledAt: '2 days ago',
    icon: 'IconBriefcase',
    tone: 'warning',
  },
  {
    key: 'flag-loyalty',
    name: 'Loyalty programme',
    description: 'Track repeat orders per user, surface rewards and free items on confirmation screens.',
    enabled: false,
    scope: 'Platform',
    scopeDetail: 'Q1 2027 launch',
    rolloutPercent: 0,
    lastToggledBy: 'Karabo Nkosi',
    lastToggledAt: '1 week ago',
    icon: 'IconStar',
    tone: 'info',
  },
  {
    key: 'flag-bi-weekly-invoice',
    name: 'Bi-weekly vendor invoicing',
    description: 'Send vendor invoices every 14 days instead of monthly.',
    enabled: false,
    scope: 'Platform',
    scopeDetail: 'Affects all vendors',
    rolloutPercent: 0,
    lastToggledBy: 'Ayanda Sithole',
    lastToggledAt: '3 weeks ago',
    icon: 'IconReceipt',
    tone: 'info',
  },
];

export const NOTIFICATION_TEMPLATES = [
  {
    key: 'order_confirmed',
    name: 'Order confirmed',
    description: 'Triggered after payment + vendor acceptance.',
    titleTemplate: 'Order #{orderNumber} confirmed',
    bodyTemplate: 'Hi {firstName}, we just confirmed your order at {vendorName}. Pick it up around {slot}.',
    enabledChannels: ['in_app', 'push'],
    isActive: true,
    updatedBy: 'Nomvula Dube',
    updatedAt: '2025-09-01 · 12:00',
  },
  {
    key: 'order_ready',
    name: 'Order ready for collection',
    description: 'Triggered when the vendor marks the order ready.',
    titleTemplate: 'Your order is ready',
    bodyTemplate: 'Show your QR at the {counterLabel} counter in {building} to grab your meal.',
    enabledChannels: ['in_app', 'push', 'email'],
    isActive: true,
    updatedBy: 'Nomvula Dube',
    updatedAt: '2025-09-01 · 12:00',
  },
  {
    key: 'order_delayed',
    name: 'Order delayed',
    description: 'Auto-triggered when prep_time exceeds the slot limit by 5+ minutes.',
    titleTemplate: 'Your order is running late',
    bodyTemplate: 'Heads up — {vendorName} is {delayMinutes} min behind. Updated ETA: {newEta}.',
    enabledChannels: ['in_app'],
    isActive: true,
    updatedBy: 'Nomvula Dube',
    updatedAt: '2025-09-01 · 12:00',
  },
  {
    key: 'refund_processed',
    name: 'Refund processed',
    description: 'Sent when an admin or vendor initiates a refund.',
    titleTemplate: 'Refund processed · Order #{orderNumber}',
    bodyTemplate: 'Your refund of {refundAmount} is on its way to {cardLast4}. Allow 1–2 business days.',
    enabledChannels: ['in_app', 'email'],
    isActive: true,
    updatedBy: 'Nomvula Dube',
    updatedAt: '2025-09-01 · 12:00',
  },
  {
    key: 'pickup_reminder',
    name: 'Pickup reminder',
    description: '15-minute pre-collection nudge for collection orders.',
    titleTemplate: 'Reminder · order #{orderNumber}',
    bodyTemplate: 'Your order is almost ready. Don’t forget your QR code at {counterLabel}.',
    enabledChannels: ['in_app', 'push'],
    isActive: true,
    updatedBy: 'Nomvula Dube',
    updatedAt: '2025-09-01 · 12:00',
  },
];

export const MAINTENANCE_WINDOWS = [
  {
    id: 'mw-1',
    title: 'Weekly DB vacuum',
    message: 'Brief scheduled maintenance — orders still process. Vendor portal may be unavailable for 5 minutes.',
    startsAt: '2026-09-07 · 03:00',
    endsAt: '2026-09-07 · 03:30',
    isActive: 'scheduled',
    createdBy: 'Ops Team',
    createdAt: '2026-08-12 · 11:18',
  },
  {
    id: 'mw-2',
    title: 'Payment provider migration window',
    message: 'Order placement will pause for ~30 minutes while we cut over payment processors.',
    startsAt: '2026-09-12 · 01:00',
    endsAt: '2026-09-12 · 01:45',
    isActive: 'scheduled',
    createdBy: 'Ops Team',
    createdAt: 'Yesterday',
  },
  {
    id: 'mw-3',
    title: 'Tech maintenance window — Saturday',
    message: 'The merchant platform was unavailable for ~30 minutes during our scheduled database maintenance.',
    startsAt: '2026-08-23 · 03:00',
    endsAt: '2026-08-23 · 05:00',
    isActive: 'history',
    createdBy: 'Ops Team',
    createdAt: '2026-08-22 · 11:48',
  },
];

export const SETTINGS_ACTIVITY = [
  { id: 'a1', at: 'Today · 10:14', actor: 'Nomvula Dube', action: 'Updated "Lead time minimum" 20 → 15 min', tone: 'info' },
  { id: 'a2', at: 'Yesterday · 14:50', actor: 'Thuli Mokoena', action: 'Toggled feature flag "Weekend service" — staged for North', tone: 'warning' },
  { id: 'a3', at: 'Yesterday · 14:50', actor: 'Nomvula Dube', action: 'Updated Library Bistro cancellation cutoff 15 → 10 min', tone: 'warning' },
  { id: 'a4', at: '2 days ago · 11:14', actor: 'Karabo Nkosi', action: 'Created draft "Sandton pilot cohort" rollout', tone: 'info' },
  { id: 'a5', at: '3 days ago · 09:48', actor: 'Ayanda Sithole', action: 'Updated fee rule "Bi-weekly vendor invoicing"', tone: 'info' },
  { id: 'a6', at: '1 week ago', actor: 'Nomvula Dube', action: 'Approved maintenance window "Weekly DB vacuum"', tone: 'success' },
];

export const formatCurrency = (value) =>
  value.toLocaleString('en-ZA', { style: 'currency', currency: 'ZAR', minimumFractionDigits: 0 });
